name: CI

on: [push, pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # Poetry をセットアップ
      - uses: abatilo/actions-poetry@v2

      # 依存インストール (--no-root でパッケージはインストールせず)
      - run: poetry install --no-interaction

      # Lint / Format check
      - run: poetry run ruff check .

      - run: poetry run black --check .

      # まだ mypy を厳密運用しないならコメントアウト
      # - run: poetry run mypy .

      # 単体テスト (e2e は除外)
      - run: poetry run pytest -q -m "not e2e"
