name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"

      - name: Install dependencies
        run: |
          poetry install --with dev
          poetry run pre-commit install --install-hooks

      - name: Run pre‑commit checks
        run: poetry run pre-commit run --all-files

      - name: Run pytest
        run: poetry run pytest -q
